# Generated by Django 4.2.7 on 2025-09-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0002_project_alter_task_options_alter_tasktype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_name', to='TaskManager.position'),
        ),
    ]
