# Generated by Django 4.2.7 on 2025-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0003_alter_worker_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
