# Generated by Django 4.2.7 on 2025-09-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0005_alter_worker_groups_alter_worker_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
