# Generated by Django 4.2.7 on 2025-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0006_position_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='project',
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ManyToManyField(related_name='project_team', to='TaskManager.project'),
        ),
    ]
