# Generated by Django 4.2.7 on 2025-09-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0007_remove_team_project_team_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='project',
            new_name='projects',
        ),
    ]
