# Generated by Django 4.2.7 on 2025-09-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0008_rename_project_team_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(related_name='project_team', to='TaskManager.team'),
        ),
    ]
