# Generated by Django 4.2.7 on 2025-09-18 12:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0009_remove_team_projects_project_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 18, 12, 35, 44, 434358, tzinfo=datetime.timezone.utc), message='The deadline must be in the future!')]),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
