# Generated by Django 4.2.7 on 2025-09-19 15:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0010_alter_task_options_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 19, 15, 10, 15, 382999, tzinfo=datetime.timezone.utc), message='The deadline must be in the future!')]),
        ),
    ]
