# Generated by Django 4.2.7 on 2025-09-19 15:11

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0011_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 19, 15, 11, 34, 283015, tzinfo=datetime.timezone.utc), message='The deadline must be in the future!')]),
        ),
    ]
