# Generated by Django 4.2.7 on 2025-09-19 17:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0013_tags_alter_task_deadline_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 19, 17, 3, 32, 977978, tzinfo=datetime.timezone.utc), message='The deadline must be in the future!')]),
        ),
    ]
