# Generated by Django 4.2.24 on 2025-09-25 14:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0015_rename_tags_tag_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_code']},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 9, 25, 14, 1, 18, 360453, tzinfo=datetime.timezone.utc), message='The deadline must be in the future!')]),
        ),
    ]
