from django.urls import path
from TaskManager.views import home
from TaskManager.views import (ProjectsListView,
                               ProjectDetailView,
                               ProjectCreateView,
                               ProjectUpdateView,
                               ProjectDeleteView,
                               PositionsListView,
                               PositionDetailView,
                               PositionsCreateView,
                               PositionsUpdateView,
                               PositionsDeleteView,
                               TeamsListView,
                               TeamDetailView,
                               TeamCreateView,
                               TeamUpdateView,
                               TeamDeleteView,
                               TasksListView,
                               TaskDetailView,
                               TaskCreateView,
                               TaskUpdateView,
                               TaskDeleteView,
                               TaskTypesListView,
                               TaskTypeDetailView,
                               TaskTypeCreateView,
                               TaskTypeUpdateView,
                               TaskTypeDeleteView,
                               WorkersListView,
                               WorkerDetailView,
                               WorkerCreateView,
                               WorkerUpdateView,
                               WorkerDeleteView,
                               TagsListView,
                               TagCreateView,
                               TagUpdateView,
                               TagDeleteView
                               )

urlpatterns = [
    path("", home, name="home"),
    path("projects/", ProjectsListView.as_view(), name="projects-list"),
    path("project/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="project-update"),
    path("projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"),
    path("positions/", PositionsListView.as_view(), name="positions-list"),
    path("position/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("position/create/", PositionsCreateView.as_view(), name="position-create"),
    path("position/<int:pk>/update/", PositionsUpdateView.as_view(), name="position-update"),
    path("position/<int:pk>/delete/", PositionsDeleteView.as_view(), name="position-delete"),
    path("teams/", TeamsListView.as_view(), name="teams-list"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("team/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("team/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
    path("tasks/", TasksListView.as_view(), name="tasks-list"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasktypes/", TaskTypesListView.as_view(), name="tasktypes-list"),
    path("tasktype/<int:pk>/", TaskTypeDetailView.as_view(), name="tasktype-detail"),
    path("tasktype/create/", TaskTypeCreateView.as_view(), name="tasktype-create"),
    path("tasktype/<int:pk>/update", TaskTypeUpdateView.as_view(), name="tasktype-update"),
    path("tasktype/<int:pk>/delete", TaskTypeDeleteView.as_view(), name="tasktype-delete"),
    path("workers/", WorkersListView.as_view(), name="workers-list"),
    path("worker/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("worker/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("worker/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("tags/", TagsListView.as_view(), name="tags-list"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete")
]


app_name = "TaskManager"
